sudo: required
services:
  - docker

before_install:
  docker build -t kashnyapa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kashnyapa/react-test npm test

after_success:
  # build containers
  - docker build -t kashnyapa/multi-client ./client
  - docker build -t kashnyapa/multi-nginx ./nginx
  - docker build -t kashnyapa/multi-server ./server
  - docker build -t kashnyapa/multi-worker ./worker
  
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # push image to docker hub
  - docker push kashnyapa/multi-client
  - docker push kashnyapa/multi-nginx
  - docker push kashnyapa/multi-server
  - docker push kashnyapa/multi-worker

deploy:
  provider: elasticbeanstack
  region: us-east-2
  app: docker-lessons
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-336811532115
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY